#!/bin/bash

# chargement des modules
module load intel-compiler/15.0.1
module load intel-mkl/11.2.1
module load intel-mpi/5.0.2
module load phdf5/1.8.15
module load valgrind/3.7.0
module load fftw/3.3.4-intelmpi5.0.2


# On se place dans le repertoire depuis lequel le job a ete soumis
cd $PBS_O_WORKDIR

cat $PBS_NODEFILE | uniq > mpd.hosts
nb_nodes=`cat mpd.hosts|wc -l`

if [ "$Run" -eq "1" ]; then
    echo "Running ScaRL"
    mpirun -np $NP /home/carvalhol/Projects/ScaRL/build/ScaRL.exe>oi
fi 
