#!/bin/bash

#PBS -S /bin/bash
#PBS -N st1-rand
#PBS -o out_stat.txt
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=1:mpiprocs=1:mem=15gb
#PBS -m e -M lucianopaludoecp@gmail.com
#PBS -q iceq

#chargement des modules
module purge
module load intel-compiler/15.0.1
module load intel-mkl/11.2.1
module load intel-mpi/5.0.2
module load phdf5/1.8.15
module load fftw/3.3.4-intelmpi5.0.2


#On se place dans le reportoire depuis lequel le job a ete soumis
cd $PBS_O_WORKDIR
mpirun -np 1 /home/carvalhol/Projects/RANDOM_FIELD/build/statistics.exe<input_stat
